channel_create:
  path: /channel/{cname}
  defaults: { _controller: AppBundle:Channel:createChannel }
  methods: [POST]

trackable_create:
  path: /channel/{cname}/trackable
  defaults: { _controller: AppBundle:Trackable:addTrackable }
  methods: [POST]

scene_create:
  path: /channel/{cname}/scene
  defaults: { _controller: AppBundle:Scene:createScene }
  methods: [POST]

