channel_create:
  path: /channel/{name}
  defaults: { _controller: AppBundle:Channel:createChannel }
  methods: [PUT]
channel_list:
  path: /channel
  defaults: { _controller: AppBundle:Channel:listChannels}
  methods: [GET]
channel_delete:
  path: /channel/{name}
  defaults: { _controller: AppBundle:Channel:deleteChannel }
  methods: [DELETE]
channel_list_files:
  path: /channel/list/files
  defaults: { _controller: AppBundle:Channel:listChannelFiles }
channel_list_versions:
  path: /channel/list/versions
  defaults: { _controller: AppBundle:Channel:listChannelVersions }



version_create:
  path: /version/create
  defaults: { _controller: AppBundle:Version:create }
version_delete:
  path: /version/delete
  defaults: { _controller: AppBundle:Version:delete }
version_current:
  path: /version/current/set
  defaults: { _controller: AppBundle:Version:setCurrent }

create_file:
  path: /file/create
  defaults: { _controller: AppBundle:File:addFile }
get_file:
  path: /file
  defaults: { _controller: AppBundle:File:getFile }
