channel_create:
  path: /channel/{name}
  defaults: { _controller: AppBundle:Channel:createChannel }
  methods: [PUT]

channel_delete:
  path: /channel/{name}
  defaults: { _controller: AppBundle:Channel:deleteChannel }
  methods: [DELETE]

channel_list:
  path: /channel
  defaults: { _controller: AppBundle:Channel:listChannels}
  methods: [GET]

channel_versions_list:
  path: /channel/{cname}/version
  defaults: { _controller: AppBundle:Version:listChannelVersions }
  methods: [GET]

channel_current:
  path: /channel/{cname}/current
  defaults: { _controller: AppBundle:Version:getCurrentVersion }
  methods: [GET]

channel_current_set:
  path: /channel/{cname}/current/{vname}
  defaults: { _controller: AppBundle:Version:setCurrentVersion }
  methods: [PUT,POST]


version_create:
  path: channel/{cname}/version/{vname}
  defaults: { _controller: AppBundle:Version:createVersion }
  methods: [PUT]

version_delete:
  path: channel/{cname}/version/{vname}
  defaults: { _controller: AppBundle:Version:delete }
  methods: [DELETE]




create_file:
  path: /channel/{cname}/version/{vname}/file
  defaults: { _controller: AppBundle:File:addFile }

get_file:
  path: /channel/{cname}/version/{vname}/file
  defaults: { _controller: AppBundle:File:getFile }
