channel_list:
  path: /channel/list
  defaults: { _controller: AppBundle:Channel:list}
channel_create:
  path: /channel/create
  defaults: { _controller: AppBundle:Channel:create }
channel_delete:
  path: /channel/delete
  defaults: { _controller: AppBundle:Channel:delete }
channel_list_files:
  path: /channel/list/files
  defaults: { _controller: AppBundle:Channel:listFiles }



version_create:
  path: /version/create
  defaults: { _controller: AppBundle:Version:create }
version_delete:
  path: /version/delete
  defaults: { _controller: AppBundle:Version:delete }
version_current:
  path: /version/current/set
  defaults: { _controller: AppBundle:Version:setCurrent }

create_file:
  path: /file/create
  defaults: { _controller: AppBundle:File:addFile }
get_file:
  path: /file
  defaults: { _controller: AppBundle:File:getFile }
