# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  file_system_provider:
    class: Symfony\Component\Filesystem\Filesystem
    arguments: []
  file_system_manager:
    class: AppBundle\Service\FileSystem\FileSystem
    arguments: [@file_system_provider,%upload_root_dir%]


  channel.subscriber:
    class: AppBundle\Subscriber\ChannelSubscriber
    arguments: [@file_system_manager]
    tags:
      - { name:  kernel.event_subscriber  }

  version.subscriber:
    class: AppBundle\Subscriber\VersionSubscriber
    arguments: [@file_system_manager]
    tags:
      - { name:  kernel.event_subscriber}

