# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  file_system_provider:
    class: Symfony\Component\Filesystem\Filesystem
    arguments: []

  file_factory:
    class: AppBundle\Service\FileSystem\FileFactory
    arguments: [@file_system_provider,%temp_root_dir%]


  file_manager:
    class: AppBundle\Service\FileSystem\FileManager
    arguments: [@file_factory,%upload_root_dir%]


  channel.subscriber:
    class: AppBundle\Subscriber\ChannelSubscriber
    arguments: [@file_manager]
    tags:
      - { name:  kernel.event_subscriber  }

  version.subscriber:
    class: AppBundle\Subscriber\VersionSubscriber
    arguments: [@file_manager]
    tags:
      - { name:  kernel.event_subscriber}

  file.subscriber:
    class: AppBundle\Subscriber\FileSubscriber
    arguments: [@file_manager]
    tags:
      - { name: kernel.event_subscriber }
